app/home/forms.py
# -*- coding:utf-8 _*-  
""" 
@author: ronething 
@file: forms.py 
@time: 2018/10/21
@github: github.com/ronething 

Less is more.
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, \
    SubmitField, FileField, TextAreaField, \
    SelectField, SelectMultipleField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from app.models import User


class RegisterForm(FlaskForm):
    """
    会员注册表单
    """
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入昵称！",
            "required": False
        }
    )

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入昵称！"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！",
            "required": False
        }
    )

    phone = StringField(
        label="手机号码",
        validators=[
            DataRequired("请输入手机号码！"),
            Regexp(r"1[3-9]\d{9}$", message="手机格式不正确！")
        ],
        description="手机号码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号码！",
            "required": False
        }
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
            "required": False
        }
    )

    re_pwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo("pwd", message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码！",
            "required": False
        }
    )

    submit = SubmitField(
        "注册",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("昵称已经存在")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮件已经存在")

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号码已经存在")


class LoginForm(FlaskForm):
    """
    会员登陆表单
    """
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号！")
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入账号！",
            "required": False
        }
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
            "required": False
        }
    )

    submit = SubmitField(
        "登录",
        render_kw={
            "class": "btn btn-lg btn-primary btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        count = User.query.filter_by(name=name).count()
        if count == 0:
            raise ValidationError("账号不存在！")


class UserDetailForm(FlaskForm):
    """
    会员详情表单
    """
    name = StringField(
        label="昵称",
        description="昵称",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入昵称！",
            "readonly": "readonly",
            "required": False
        }
    )

    email = StringField(
        label="邮箱",
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
            "readonly": "readonly",
            "required": False
        }
    )

    phone = StringField(
        label="手机号码",
        description="手机号码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号码！",
            "readonly": "readonly",
            "required": False
        }
    )

    logo = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像")
        ],
        description="头像",
        render_kw={
            "required": False
        }
    )

    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": "10",
            "required": False
        }
    )

    submit = SubmitField(
        "保存修改",
        render_kw={
            "class": "btn btn-primary"
        }
    )


class PwdForm(FlaskForm):
    """
    密码表单
    """
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码！",
            "required": False
        }
    )

    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码！")
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码！",
            "required": False
        }
    )

    check_pwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo("new_pwd", message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入确认密码！",
            "required": False
        }
    )

    submit = SubmitField(
        "修改密码",
        render_kw={
            "class": "btn btn-primary"
        }
    )

    def validate_old_pwd(self, field):
        from flask import session, flash
        old_pwd = field.data
        if session.get("user_id") is None:
            raise ValidationError("不谈了！")
        user_id = session["user_id"]
        user = User.query.filter_by(id=user_id).first()
        if not user.check_pwd(old_pwd):
            flash("旧密码错误！", "err")
            raise ValidationError("旧密码错误！")


class CommentForm(FlaskForm):
    """
    评论表单
    """
    content =TextAreaField(
        label="评论内容",
        validators=[
            DataRequired("请输入评论内容"),
        ],
        description="评论内容",
        render_kw={
            "required": False
        }
    )

    submit = SubmitField(
        "提交评论",
        render_kw={
            "class": "btn btn-success",
        }
    )

app/home/__init__.py
# -*- coding:utf-8 _*-  
""" 
@author: ronething 
@file: __init__.py.py 
@time: 2018/10/21
@github: github.com/ronething 

Less is more.
"""

from flask import Blueprint


home = Blueprint("home", __name__)

# views 不能放在 home blueprint 前面 否则会报错
import app.home.views

app/home/views.py
# -*- coding:utf-8 _*-  
""" 
@author: ronething 
@file: views.py 
@time: 2018/10/21
@github: github.com/ronething 

Less is more.
"""

import uuid
import os
import datetime
import json

from . import home
from flask import render_template, redirect, url_for, flash, session, request, Response
from app.home.forms import RegisterForm, LoginForm, UserDetailForm, PwdForm, CommentForm
from app.models import User, Userlog, Preview, Tag, Movie, Comment, Moviecol
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from pypinyin import lazy_pinyin
from app import db, app
from functools import wraps


# 登陆控制装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get("user_name") is None:
            return redirect(url_for("home.login", next=request.url))  # 和 第 410 行 request.args.get("next") 联动
        return f(*args, **kwargs)

    return decorated_function


# 修改文件名称
def rename_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") \
               + uuid.uuid4().hex \
               + fileinfo[-1]

    return filename


# 前台首页
@home.route("/", methods=["GET"])
@home.route("/<int:page>/", methods=["GET"])
def index(page=None):
    tags = Tag.query.all()
    star_list = ["一", "二", "三", "四", "五"]
    page_data = Movie.query

    tag_id = request.args.get("tid", 0)
    if int(tag_id) != 0:
        page_data = page_data.filter_by(tag_id=int(tag_id))
    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
    time = request.args.get("time", 0)
    if int(time) == 0:
        page_data = page_data.order_by(
            Movie.addtime.desc()
        )
    else:
        page_data = page_data.order_by(
            Movie.addtime.asc()
        )
    pm = request.args.get("pm", 0)
    if int(pm) == 0:
        page_data = page_data.order_by(
            Movie.playnum.desc()
        )
    else:
        page_data = page_data.order_by(
            Movie.playnum.asc()
        )
    cm = request.args.get("cm", 0)
    if int(cm) == 0:
        page_data = page_data.order_by(
            Movie.commentnum.desc()
        )
    else:
        page_data = page_data.order_by(
            Movie.commentnum.asc()
        )

    param = dict(
        tid=tag_id,
        star=star,
        time=time,
        pm=pm,
        cm=cm,
    )

    if page is None:
        page = 1
    page_data = page_data.paginate(page=page, per_page=12)

    return render_template("home/index.html", tags=tags, param=param, star_list=star_list, page_data=page_data)


# 会员登陆
@home.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data["name"]).first()
        if not user.check_pwd(data["pwd"]):
            flash("密码错误！", "err")
            return redirect(url_for("home.login", next=request.args.get("next", "")))
        session["user_name"] = data["name"]
        session["user_id"] = user.id
        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(request.args.get("next") or url_for("home.user"))
    return render_template("home/login.html", form=form)


# 会员注销
@home.route("/logout/")
def logout():
    session.pop("user_name", None)
    session.pop("user_id", None)
    return redirect(url_for("home.index"))


# 会员注册
# TODO 需要把 "这个人很懒，什么都没有留下" 这些类似的字符串 放在一个单独的文件里面当常量咯
@home.route("/register/", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            email=data["email"],
            phone=data["phone"],
            pwd=generate_password_hash(data["pwd"]),
            info="这个人很懒，什么都没有留下",
            face="face.jpg",
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功，请登录！", "ok")
        return redirect(url_for("home.login", next=request.args.get("next")))
    return render_template("home/register.html", form=form)


# 会员中心
@home.route("/user/", methods=["GET", "POST"])
@user_login_req
def user():
    form = UserDetailForm()
    form.logo.validators = []
    user = User.query.filter_by(id=session["user_id"]).first()
    if request.method == "GET":
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        if not os.path.exists(app.config["LOGO_DIR"]):
            os.makedirs(app.config["LOGO_DIR"])
            os.chmod(app.config["LOGO_DIR"], "rw")
        if form.logo.data:
            file_logo = secure_filename("".join(lazy_pinyin(form.logo.data.filename)))
            user.face = rename_filename(file_logo)
            form.logo.data.save(app.config["LOGO_DIR"] + user.face)
        user.info = data["info"]
        db.session.add(user)
        db.session.commit()
        flash("修改资料成功", "ok")
        return redirect(url_for("home.user"))
    return render_template("home/user.html", form=form, user=user)


# 修改密码
@home.route("/pwd/", methods=["GET", "POST"])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user_id = session["user_id"]
        user = User.query.filter_by(id=user_id).first()
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功，请重新登陆！", "ok")
        return redirect(url_for("home.logout"))
    return render_template("home/pwd.html", form=form)


# 评论记录
@home.route("/comments/", methods=["GET"])
@home.route("/comments/<int:page>/", methods=["GET"])
@user_login_req
def comments(page=None):
    if page is None:
        page = 1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Comment.movie_id,
        User.id == session["user_id"]
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=5)
    return render_template("home/comments.html", page_data=page_data)


# 登陆日志
@home.route("/loginlog/", methods=["GET"])
@home.route("/loginlog/<int:page>/", methods=["GET"])
@user_login_req
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = Userlog.query.filter_by(
        user_id=session["user_id"]
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/loginlog.html", page_data=page_data)


# 电影收藏添加 ajax 返回 json
@home.route("/moviecol/add/", methods=["GET"])
@user_login_req
def moviecol_add():
    mid = request.args.get("mid", "")
    moviecol_count = Moviecol.query.filter_by(
        user_id=session["user_id"],
        movie_id=int(mid),
    ).count()
    if moviecol_count == 1:
        data = dict(
            ok=0,
            message="不可重复收藏"
        )

        return json.dumps(data)

    if moviecol_count == 0:
        movie_col = Moviecol(
            user_id=session["user_id"],
            movie_id=int(mid)
        )
        db.session.add(movie_col)
        db.session.commit()
        data = dict(
            ok=1,
            message="收藏电影成功"
        )

    return json.dumps(data)


# 电影收藏
@home.route("/moviecol/", methods=["GET"])
@home.route("/moviecol/<int:page>/", methods=["GET"])
@user_login_req
def moviecol(page=None):
    if page is None:
        page = 1
    page_data = Moviecol.query.join(
        Movie
    ).filter(
        Movie.id == Moviecol.movie_id,
        Moviecol.user_id == session["user_id"],
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page, per_page=5)
    return render_template("home/moviecol.html", page_data=page_data)


# 上映预告轮播
@home.route("/animation/")
def animation():
    data = Preview.query.order_by(
        Preview.addtime.desc()
    ).paginate(page=1, per_page=5)
    return render_template("home/animation_bootstrap.html", data=data)


# 搜索
@home.route("/search/", methods=["GET"])
@home.route("/search/<int:page>/", methods=["GET"])
def search(page=None):
    key = request.args.get("s", "")
    if not key:
        return redirect(url_for("home.index"))
    if page is None:
        page = 1
    count = Movie.query.filter(
        # ilike 和 like 类似 不过 ilike 忽略大小写
        Movie.title.ilike('%' + key + '%')
    ).count()
    page_data = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page, per_page=5)
    return render_template("home/search.html", page_data=page_data, key=key, count=count)


# 电影详情
@home.route("/play/<int:id>/", methods=["GET", "POST"])
@home.route("/play/<int:id>/<int:page>/", methods=["GET", "POST"])
def play(id=None, page=None):
    movie = Movie.query.join(
        Tag
    ).filter(
        Movie.id == id,
        Movie.tag_id == Tag.id
    ).first_or_404()
    form = CommentForm()

    # 评论列表
    if page is None:
        page = 1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == movie.id,
        User.id == Comment.user_id
    ).order_by(
        Comment.addtime.asc()
    ).paginate(page=page, per_page=10)

    # comment_count = Comment.query.join(
    #     Movie
    # ).join(
    #     User
    # ).filter(
    #     Movie.id == movie.id,
    #     User.id == Comment.user_id
    # ).count()

    movie.playnum = movie.playnum + 1
    if "user_id" in session and form.validate_on_submit():
        data = form.data
        # TODO content 插入的时候需要过滤一些特殊字符 防止注入攻击之类的
        comment = Comment(
            content=data["content"],
            movie_id=movie.id,
            user_id=session["user_id"]
        )
        db.session.add(comment)
        movie.commentnum = movie.commentnum + 1
        db.session.add(movie)

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input class="form-control" placeholder="请输入电影名" id="search_value">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search_submit" href="{{ url_for('home.search') }}"><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if "user_id" not in session %}
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                {% endif %}
                {% if "user_id" in session %}
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                {% endif %}
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2018 ronething
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/holder.min.js') }}"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
    $(function () {
        $("#search_value").bind('input propertychange', function () {
            var val = $(this).val();
            $("#search_submit").attr("href", "{{ url_for('home.search') }}?s=" + val);
        })
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名" id="search_value">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search_submit" href="{{ url_for('home.search') }}"><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if "user_id" not in session %}
                <li>
                    <a class="curlink" href="{{ url_for('home.login', next=request.url) }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register', next=request.url) }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                {% endif %}
                {% if "user_id" in session %}
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                {% endif %}
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content %}{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2018 ronething
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/holder.min.js') }}"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
    $(function () {
        $("#search_value").bind('input propertychange', function () {
            var val = $(this).val();
            $("#search_submit").attr("href", "{{ url_for('home.search') }}?s=" + val);
        })
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments') }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.loginlog') }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecol') }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>

app/templates/home/search.html
{% extends "home/home.html" %}

{% import "common/search_pagination.html" as pagination %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb" style="margin-top:6px;">
            <li>与"{{ key }}"有关的电影，共{{ count }}部</li>
        </ol>
    </div>
    <div class="col-md-12">
        {% for i in page_data.items %}
        <div class="media">
            <div class="media-left">
                <a href="{{ url_for('home.video', id=i.id) }}">
                    <img class="media-object" style="width: 131px" src="{{ url_for('static', filename='uploads/' + i.logo) }}" alt="{{ i.tile }}">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">{{ i.title }}<a href="{{ url_for('home.video', id=i.id) }}" class="label label-primary pull-right"><span
                        class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                {{ i.info }}
            </div>
        </div>
        {% endfor %}
    </div>
    {% if page_data.items %}
    <div class="col-md-12 text-center">
         {{ pagination.page(page_data, "home.search", key) }}
    </div>
    {% endif %}
</div>
{% endblock %}